<h1>Array</h1>
<p><em>Array</em> instance</p>
<h2><code>array/is</code></h2>
<p>Confirms if given object is a native array</p>
<pre><code class="language-javascript">const isArray = require(&quot;type/array/is&quot;);

isArray([]); // true
isArray({}); // false
isArray(&quot;foo&quot;); // false
</code></pre>
<h2><code>array/ensure</code></h2>
<p>If given argument is an array, it is returned back. Otherwise <code>TypeError</code> is thrown.</p>
<pre><code class="language-javascript">const ensureArray = require(&quot;type/array/ensure&quot;);

ensureArray([&quot;foo&quot;]); // [&quot;foo&quot;]
ensureArray(&quot;foo&quot;); // Thrown TypeError: foo is not an array
</code></pre>
<h3>Confirming on items</h3>
<p>Items can be validated by passing <code>ensureItem</code> option. Note that in this case:</p>
<ul>
<li>A newly created instance of an array with coerced item values is returned</li>
<li>Error message lists up to three items which are invalid</li>
</ul>
<pre><code class="language-javascript">const ensureString = require(&quot;type/string/ensure&quot;);

ensureArray([12], { ensureItem: ensureString }); // [&quot;12&quot;]

/*
 Below invocation with crash with:
 TypeError: 23, [object Object], [object Object] is not a valid array.
            Following items are invalid: [object Object], [object Object]
*/
ensureArray([23, {}, {}], { ensureItem: ensureString });
</code></pre>
