<h2>Errors</h2>
<p>NAN includes helpers for creating, throwing and catching Errors as much of this functionality varies across the supported versions of V8 and must be abstracted.</p>
<p>Note that an Error object is simply a specialized form of <code>v8::Value</code>.</p>
<p>Also consult the V8 Embedders Guide section on <a href="https://developers.google.com/v8/embed#exceptions">Exceptions</a> for more information.</p>
<ul>
<li>&lt;a href=&quot;#api_nan_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::Error()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_range_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::RangeError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_reference_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ReferenceError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_syntax_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::SyntaxError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_type_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::TypeError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_throw_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ThrowError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_throw_range_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ThrowRangeError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_throw_reference_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ThrowReferenceError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_throw_syntax_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ThrowSyntaxError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_throw_type_error&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ThrowTypeError()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_fatal_exception&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::FatalException()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_errno_exception&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::ErrnoException()&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
<li>&lt;a href=&quot;#api_nan_try_catch&quot;&gt;&lt;b&gt;&lt;code&gt;Nan::TryCatch&lt;/code&gt;&lt;/b&gt;&lt;/a&gt;</li>
</ul>
<p>&lt;a name=&quot;api_nan_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::Error()</h3>
<p>Create a new Error object using the <a href="https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html">v8::Exception</a> class in a way that is compatible across the supported versions of V8.</p>
<p>Note that an Error object is simply a specialized form of <code>v8::Value</code>.</p>
<p>Signature:</p>
<pre><code class="language-c++">v8::Local&lt;v8::Value&gt; Nan::Error(const char *msg);
v8::Local&lt;v8::Value&gt; Nan::Error(v8::Local&lt;v8::String&gt; msg);
</code></pre>
<p>&lt;a name=&quot;api_nan_range_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::RangeError()</h3>
<p>Create a new RangeError object using the <a href="https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html">v8::Exception</a> class in a way that is compatible across the supported versions of V8.</p>
<p>Note that an RangeError object is simply a specialized form of <code>v8::Value</code>.</p>
<p>Signature:</p>
<pre><code class="language-c++">v8::Local&lt;v8::Value&gt; Nan::RangeError(const char *msg);
v8::Local&lt;v8::Value&gt; Nan::RangeError(v8::Local&lt;v8::String&gt; msg);
</code></pre>
<p>&lt;a name=&quot;api_nan_reference_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ReferenceError()</h3>
<p>Create a new ReferenceError object using the <a href="https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html">v8::Exception</a> class in a way that is compatible across the supported versions of V8.</p>
<p>Note that an ReferenceError object is simply a specialized form of <code>v8::Value</code>.</p>
<p>Signature:</p>
<pre><code class="language-c++">v8::Local&lt;v8::Value&gt; Nan::ReferenceError(const char *msg);
v8::Local&lt;v8::Value&gt; Nan::ReferenceError(v8::Local&lt;v8::String&gt; msg);
</code></pre>
<p>&lt;a name=&quot;api_nan_syntax_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::SyntaxError()</h3>
<p>Create a new SyntaxError object using the <a href="https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html">v8::Exception</a> class in a way that is compatible across the supported versions of V8.</p>
<p>Note that an SyntaxError object is simply a specialized form of <code>v8::Value</code>.</p>
<p>Signature:</p>
<pre><code class="language-c++">v8::Local&lt;v8::Value&gt; Nan::SyntaxError(const char *msg);
v8::Local&lt;v8::Value&gt; Nan::SyntaxError(v8::Local&lt;v8::String&gt; msg);
</code></pre>
<p>&lt;a name=&quot;api_nan_type_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::TypeError()</h3>
<p>Create a new TypeError object using the <a href="https://v8docs.nodesource.com/node-8.16/da/d6a/classv8_1_1_exception.html">v8::Exception</a> class in a way that is compatible across the supported versions of V8.</p>
<p>Note that an TypeError object is simply a specialized form of <code>v8::Value</code>.</p>
<p>Signature:</p>
<pre><code class="language-c++">v8::Local&lt;v8::Value&gt; Nan::TypeError(const char *msg);
v8::Local&lt;v8::Value&gt; Nan::TypeError(v8::Local&lt;v8::String&gt; msg);
</code></pre>
<p>&lt;a name=&quot;api_nan_throw_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ThrowError()</h3>
<p>Throw an Error object (a specialized <code>v8::Value</code> as above) in the current context. If a <code>msg</code> is provided, a new Error object will be created.</p>
<p>Signature:</p>
<pre><code class="language-c++">void Nan::ThrowError(const char *msg);
void Nan::ThrowError(v8::Local&lt;v8::String&gt; msg);
void Nan::ThrowError(v8::Local&lt;v8::Value&gt; error);
</code></pre>
<p>&lt;a name=&quot;api_nan_throw_range_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ThrowRangeError()</h3>
<p>Throw an RangeError object (a specialized <code>v8::Value</code> as above) in the current context. If a <code>msg</code> is provided, a new RangeError object will be created.</p>
<p>Signature:</p>
<pre><code class="language-c++">void Nan::ThrowRangeError(const char *msg);
void Nan::ThrowRangeError(v8::Local&lt;v8::String&gt; msg);
void Nan::ThrowRangeError(v8::Local&lt;v8::Value&gt; error);
</code></pre>
<p>&lt;a name=&quot;api_nan_throw_reference_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ThrowReferenceError()</h3>
<p>Throw an ReferenceError object (a specialized <code>v8::Value</code> as above) in the current context. If a <code>msg</code> is provided, a new ReferenceError object will be created.</p>
<p>Signature:</p>
<pre><code class="language-c++">void Nan::ThrowReferenceError(const char *msg);
void Nan::ThrowReferenceError(v8::Local&lt;v8::String&gt; msg);
void Nan::ThrowReferenceError(v8::Local&lt;v8::Value&gt; error);
</code></pre>
<p>&lt;a name=&quot;api_nan_throw_syntax_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ThrowSyntaxError()</h3>
<p>Throw an SyntaxError object (a specialized <code>v8::Value</code> as above) in the current context. If a <code>msg</code> is provided, a new SyntaxError object will be created.</p>
<p>Signature:</p>
<pre><code class="language-c++">void Nan::ThrowSyntaxError(const char *msg);
void Nan::ThrowSyntaxError(v8::Local&lt;v8::String&gt; msg);
void Nan::ThrowSyntaxError(v8::Local&lt;v8::Value&gt; error);
</code></pre>
<p>&lt;a name=&quot;api_nan_throw_type_error&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ThrowTypeError()</h3>
<p>Throw an TypeError object (a specialized <code>v8::Value</code> as above) in the current context. If a <code>msg</code> is provided, a new TypeError object will be created.</p>
<p>Signature:</p>
<pre><code class="language-c++">void Nan::ThrowTypeError(const char *msg);
void Nan::ThrowTypeError(v8::Local&lt;v8::String&gt; msg);
void Nan::ThrowTypeError(v8::Local&lt;v8::Value&gt; error);
</code></pre>
<p>&lt;a name=&quot;api_nan_fatal_exception&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::FatalException()</h3>
<p>Replaces <code>node::FatalException()</code> which has a different API across supported versions of Node. For use with <a href="#api_nan_try_catch"><code>Nan::TryCatch</code></a>.</p>
<p>Signature:</p>
<pre><code class="language-c++">void Nan::FatalException(const Nan::TryCatch&amp; try_catch);
</code></pre>
<p>&lt;a name=&quot;api_nan_errno_exception&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::ErrnoException()</h3>
<p>Replaces <code>node::ErrnoException()</code> which has a different API across supported versions of Node.</p>
<p>Signature:</p>
<pre><code class="language-c++">v8::Local&lt;v8::Value&gt; Nan::ErrnoException(int errorno,
                                         const char* syscall = NULL,
                                         const char* message = NULL,
                                         const char* path = NULL);
</code></pre>
<p>&lt;a name=&quot;api_nan_try_catch&quot;&gt;&lt;/a&gt;</p>
<h3>Nan::TryCatch</h3>
<p>A simple wrapper around <a href="https://v8docs.nodesource.com/node-8.16/d4/dc6/classv8_1_1_try_catch.html"><code>v8::TryCatch</code></a> compatible with all supported versions of V8. Can be used as a direct replacement in most cases. See also <a href="#api_nan_fatal_exception"><code>Nan::FatalException()</code></a> for an internal use compatible with <code>node::FatalException</code>.</p>
<p>Signature:</p>
<pre><code class="language-c++">class Nan::TryCatch {
 public:
  Nan::TryCatch();

  bool HasCaught() const;

  bool CanContinue() const;

  v8::Local&lt;v8::Value&gt; ReThrow();

  v8::Local&lt;v8::Value&gt; Exception() const;

  // Nan::MaybeLocal for older versions of V8
  v8::MaybeLocal&lt;v8::Value&gt; StackTrace() const;

  v8::Local&lt;v8::Message&gt; Message() const;

  void Reset();

  void SetVerbose(bool value);

  void SetCaptureMessage(bool value);
};
</code></pre>
